### ISSUE TITLE
Job Postings

### ISSUE THREAD

**Issue by KasiaWM** [trinitywebmedia/Norwescap-Tickets#11]
Peggy is unable to post jobs.

I am reaching out to ask if something has changed on your end (it has on our end) with the  job postings.
I am not able to  post any  new jobs.  I got a message saying that I have to fill out a form (which I cannot find)  & than I should wait  24hrs before it  can be reviewed & than, hopefully,
I will see it on the website.  If things have changed & this is our new procedure,  can you please reach out & let me know. Also I have 5 postings that are sitting on my desk waiting.

**Comment by trinitywebmedia** [comment]
Nothing procedural changed on our end since the last fix a couple of months ago. I will review and let you know what we find here. -- GT

**Comment by trinitywebmedia** [comment]
<img width="1117" alt="Screen Shot 2021-05-18 at 4 36 13 PM" src="https://user-images.githubusercontent.com/31321275/118720162-448f9e00-b7f7-11eb-817c-39dbe7db6f72.png">
Here are the last jobs posted....all look like a valid post to me.  I will delete that last one since the only content is 'Test Test Test' -- GT

All jobs should be posted by filling out the form at: https://norwescap.org/job-posting-system/ 
pw: Norwescap Jobs

**Comment by trinitywebmedia** [comment]
All jobs once posted post to https://norwescap.org/jobs/ -- GT

**Comment by trinitywebmedia** [comment]
Please let us know if Peggy has any other issues. I will leave this ticket open for now, and close tomorrow if no other actions are required. -- GT
