### ISSUE TITLE
Update to homepage

### ISSUE THREAD

**Issue by hlthomps** [trinitywebmedia/Norwescap-Tickets#111]
Good morning,

We would like to add the following text and attached graphic to the homepage above the "Carrie Ann" section. I am not sure the best way to lay this out within our template and so that it works on both desktop and mobile so I will leave that to you. Please let me know if you have any questions or run into any issues.

**Overcome the pandemic blues by making your health your priority! Join us on April 11** to discover the resources you need to become a healthier version of yourself, along with information to help with food, heating, child care, WIC, nutrition, and financial empowerment. Free food, raffle prizes, giveaways and more! Click here for more details.

Click here in the last sentence should link to our events page https://norwescap.org/upcoming-events/

![Trinity - NorwescapHealth - 1000 × 600 px](https://user-images.githubusercontent.com/83599303/161989136-e73470b3-326b-4db9-b2e7-c96eb993ee55.jpg)

**Comment by trinitywebmedia** [comment]
Thank you for the details. The text will work perfectly on mobile devices but any images will shrink in scale to fit the size of the device. Moving forward, when we discuss the re-build we can talk about how to accommodate event design elements to make sure they are visually appealing.

I will tackle this dev within April's hours in order to preserve the other block of time, unless you want to account for it differently. 

Thanks -- GT

**Comment by trinitywebmedia** [comment]
DONE -- 1 hr 45 min remaining for April. 
Thanks -- GT
