### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by KasiaWM** [trinitywebmedia/Norwescap-Tickets#15]
Hey, 
So thanks for taking care of the home page this am..
One tiny bit of confusion... 
See the buttons there.. Norwescap Programs | Events| Get Involved| Get Assistance 

Where I was going with the NorwesFest button... was to replace the Events button there... Not the Get Assistance, cause people actually use that. We don't use the Events button at all so I figured it would be the perfect place to put NorwesFest Info.

The way you set up the button istelf is perfect.  and I think its very very clear.  Can you just remove the Events button and put back the Get Assistance button in its place and we are good to go.

Regarding the whole covid section... correct me if im wrong... if we delete content out of there its still a section correct?  So its wiser not to get rid of it but utilize that section in a different manner?  Because if thats the case I'm thinking we may be able to figure a solid plan out for that section to make the most of it. 

LMK

**Comment by trinitywebmedia** [comment]
Ok, so it's not a button, it's a menu nav item. I can fix that this afternoon. [FIXED}

- Can you please send me the 'Get Help' link to replace what I did this morning.

Since we posted all Covid related items as a 'post' there is an archive of the posts. Replacing the homepage section does not affect the archive. Please let me know if you want the 'Covid' archive items to go somewhere in the navigation bar. It cannot be it's own thing, but it can possibly go under 'News'

Please adivse. -- GT

**Comment by trinitywebmedia** [comment]
<img width="1418" alt="Screen Shot 2021-05-19 at 9 08 28 AM" src="https://user-images.githubusercontent.com/31321275/118818026-dba13800-b881-11eb-8a81-2610d2d625ba.png">
Nothing I can do about the nav being pushed down with the new item.

**Comment by trinitywebmedia** [comment]
Buttons on homepage fixed. Sorry for the confusion -- GT
