### ISSUE TITLE
Add banner image to homepage

### ISSUE THREAD

**Issue by hlthomps** [trinitywebmedia/Norwescap-Tickets#82]
Hello,

We'd like to add the attached banner image to our homepage, above the "Meet Carrie Ann" section. The banner should link to this URL: https://forms.office.com/r/TWg8LbtUWv. Please let me know if there are any issues with the banner size, graphic resolution, etc.

Thank you!
Heather
![22 02 02 - Aspirations Survey banner - Home Page (1600  400 px)](https://user-images.githubusercontent.com/83599303/152432800-5912a9e2-929f-4ece-9e2c-29d7a3567fa5.png)

**Comment by trinitywebmedia** [comment]
I will work on this now. This will take more time than needed because of the constraints of the theme and how it was originally specd to build. I'll make it work, but we need to talk about a new design moving forward to accommodate changes like this. -- GT

**Comment by trinitywebmedia** [comment]
Banner is onsite and I recoded a bunch of the homepage to work. Because of how this is developed (to Kasia's specs) banners with text will never look good on mobile devices. The way it should be done is with a background image with text ovelayed over the image. 

I believe Kevin sent an email yesterday to start talking about future updates. 

Changes are done. -- GT
